### ISSUE TITLE
Sub-Categories

### ISSUE THREAD

**Issue by bastil0** [pfalcon/apps2org#2]
It would be great if I can create sub-categories inside of normal categories. For example:

> Games
> 
> > Action
> > RPG
> > Puzzle

**Comment by pfalcon** [comment]
Yes, it would be nice, but not going to happen, unless someone provides patches.

**Comment by bastil0** [comment]
Why?

**Comment by pfalcon** [comment]
Because the only way to implement something is to implement it?

**Comment by bastil0** [comment]
Why don't you want to implement it?

**Comment by bastil0** [comment]
So, no smart-ass comments anymore, dude?

**Comment by pfalcon** [comment]
By the same reasons why everyone doesn't want to do something - I don't need it (apps2org does everything want I wanted it to do), I don't have time for it, and I'm not paid for it.

Now, why don't _you_ want to implement it?
