### ISSUE TITLE
[question] pull request for willemw12/apps2org

### ISSUE THREAD

**Issue by conrad-heimbold** [pfalcon/apps2org#6]
Could you pull the UI changes by @willemw12 ( https://github.com/willemw12/apps2org ) into your app? I am new to github and I know that it is actually the fork owner's responsibility to make a pull request. IDK why he hasn't done that so far - the released app version 1.6.1 is stable. 
The F-Droid bot only monitors your repo, not willemw12's one; and having a separate app on F-Droid just for that fork is not necessary, IMHO. 
For making a pull request: https://github.com/pfalcon/apps2org/compare/master...willemw12:ui

**Comment by pfalcon** [comment]
You would still need to contact @willemw12 and ask him to do that first. But here're bad news: if his changes are about "Requirements: Android 5.0 (SDK 21) or higher.", I won't accept them. I'm strongly against production of electronic waste, and useless UI changes are what makes otherwise good and useful devices no longer work for users. Apps2Org is not like that.

**Comment by conrad-heimbold** [comment]
"You would still need to contact @willemw12 and ask him to do that first." 
No, You or I can make the pull request without asking him, because the pull request **won't change any of his files**; only the files in **your** repo, AFAIK. So only social limitations , no technical ones. 

"I'm strongly against production of electronic waste". 
Me as well. However: 
newer android version necessary =/= new hardware necessary - It is very unlikely, that there is no newer (community-maintained) android version for your device: 
- stable cyanogenmod versions for your device can be found on https://archive.org/download/cmarchive_snapshots (almost all based on android 6 / cyanogenmod 13 ). Those are very stable and have been archived. 
- not yet stable lineageos versions can be found on https://download.lineageos.org/ (based on android 7 / cyanogenmod 14 ). 

You just have to know where to look ;)

"useless UI changes". 
In my opinion, this UI change is **very** necessary. Just look at my issue #5. This can **only** be solved by using a newer UI library. 

BTW: in F-Droid, you can also install older versions of apps, if newer versions are not compatible with your device.

**Comment by pfalcon** [comment]
> So only social limitations , no technical ones.

"only"? On this planet, it's customary for humans to ask each other first before proceeding to actions.

 > stable cyanogenmod versions for your device

For *my* device (or for 10 out of my dozen), there're no cyanogenmod versions. Also, the talk is not about your or my device, but about billions of devices of billions of users in the world.

> BTW: in F-Droid, you can also install older versions of apps, if newer versions are not compatible with your device.

I know what's "possible" in F-Droid. I quitted contributing to it when then dropped support for older devices in their client.


I'm afraid, the only reasonable way for you to proceed is get to talk with @willemw12 and get his version into F-Droid.
